### ISSUE TITLE
Why not find build.js in ./src/fabric and an error occurred when I run grunt

### ISSUE THREAD

**Issue by Create-Peace** [niklasvh/html2canvas#1141]
I don't find build.js file in the ./src/fabric. When I run grunt,  The following error message appears。

```
AppledeMacBook-Pro:html2canvas apple$ grunt
Running "jshint:all" (jshint) task
>> 28 files lint free.

Running "execute:fabric" (execute) task

>> 0 files and 0 calls executed (2ms)

Running "browserify:dist" (browserify) task
>> Bundle dist/html2canvas.js created.

Running "browserify:svg" (browserify) task
>> Bundle dist/html2canvas.svg.js created.

Running "uglify:dist" (uglify) task
>> 1 file created.

Running "uglify:svg" (uglify) task
>> 1 file created.

Running "mochacli:all" (mochacli) task


  requirejs
    ✓ should have html2canvas defined


  1 passing (39ms)


Running "connect:altServer" (connect) task
Started connect web server on http://localhost:8083

Running "mocha_phantomjs:all" (mocha_phantomjs) task
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/Users/apple/Desktop/html2canvas/html2canvas/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Warning: 8 tests failed Use --force to continue.

Aborted due to warnings.

```

**Comment by niklasvh** [comment]
Fabric.js will be removed from the next release.
