### ISSUE TITLE
TypeError: Cannot read property 'createElement' of undefined on build

### ISSUE THREAD

**Issue by jularbs** [niklasvh/html2canvas#2748]
html2canvas working on local machine. But when deploying to Heroku, build fails with error:

TypeError: Cannot read property 'createElement' of undefined
    at Function.CacheStorage.setContext (/tmp/build_93fba9ee/node_modules/html2canvas/dist/html2canvas.js:5744:50)
    at /tmp/build_93fba9ee/node_modules/html2canvas/dist/html2canvas.js:7753:22
    at /tmp/build_93fba9ee/node_modules/html2canvas/dist/html2canvas.js:7:85
    at Object.<anonymous> (/tmp/build_93fba9ee/node_modules/html2canvas/dist/html2canvas.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18) {
  type: 'TypeError'
}

package.json:
    "jspdf": "^2.4.0",
    "html2canvas": "^1.3.2",
    "react": "17.0.1",
    "next": "10.0.6",

**Comment by jularbs** [comment]
Code where i used it


```

import React, { useState, useEffect } from "react";

import jsPDF from "jspdf";
import html2canvas from "html2canvas";


  const downloadDocument = (id) => {
    getHealthDeclaration(id).then((data) => {
      setDetails(data);
      const doc = document.getElementById("a4-print");
      html2canvas(doc, { allowTaint: true, useCORS: true }).then((canvas) => {
        const imgData = canvas.toDataURL("image/png");
        const pdf = new jsPDF("p", "pt", "a4", false);
        pdf.addImage(imgData, "PNG", 0, 0, 600, 0, undefined, false);
        pdf.save(`${data.fullName}_${data.createdAt}.pdf`);
      });
    });
  };
```

**Comment by niklasvh** [comment]
html2canvas is only supported in browsers, running it in node is not and won't be supported
