### ISSUE TITLE
Not working for webkit-filter

### ISSUE THREAD

**Issue by Prashu33** [niklasvh/html2canvas#493]
I'm using webkit brightness effect on canvas but while converting that canvas into new canvas these effects are not applied..

-webkit-filter: brightness(1.3);
 -moz-filter: brightness(1.3);

**Comment by moxet** [comment]
I am also waiting for filters to be implemented, @niklasvh any idea if we could do it by ourselves? Regards

**Comment by animista01** [comment]
+1. I'm waiting too

**Comment by danielfigueroa** [comment]
What about this new feature?

**Comment by jonasmiddendorf** [comment]
+1. I'm waiting too

**Comment by arsen2010** [comment]
Me too, expecting -webkit-filter:blur() work, thank you.

**Comment by zhiyan** [comment]
+ 1. waiting too

**Comment by jamesdidit** [comment]
+1

**Comment by ben-lei** [comment]
+1

**Comment by kriosguerra3** [comment]
+1

**Comment by LanderBeeuwsaert** [comment]
+1

**Comment by fernandofc** [comment]
+1

**Comment by alexkostenko** [comment]
+1

**Comment by cyan33** [comment]
I wrote a tiny library that could screenshot the image along with the css filter properties, hope it helps
https://github.com/cyan33/image-screenshot

**Comment by Prindl** [comment]
I added basic filter support into html to canvas.
https://github.com/niklasvh/html2canvas/pull/1763

**Comment by linshuizhaoying** [comment]
until 2019, it not working

if you use filter: grayscale(100%)

you can use svg to solve it.

gray.svg:

<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
    <filter id="grayscale">
        <feColorMatrix type="matrix" values="0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0"/>
    </filter>
</svg>

.xxx{
filter: url(gray.svg#grayscale);
}

It can work~

**Comment by sho-87** [comment]
+1
@Prindl @niklasvh any updates on the pull request (#1763) that was submitted for handling CSS filters?

**Comment by byeze** [comment]
Updates?

**Comment by ysk2014** [comment]
fix #2300

**Comment by ysk2014** [comment]
fix #2300

**Comment by istoan** [comment]
Lately I've been converting Flash based web apps to HTML5/CSS and JavaScript. I've been using html2canvas to capture the HTML elements and converting them into images. Only problem I've been having is that it does not support filters and webkitTextStroke . I've been trying @ysk2014 #2300 fix, but it doesn't produce good results with webkitTextStroke and filters doesn't seem to be supported at all. I've tested with the Blur filter and the Shadow filter.

**Comment by ysk2014** [comment]
@istoan Can you provide some examples of not working? All the examples I wrote are in the tests folder：

- tests/reftests/images/filter.html
- tests/reftests/text/stroke.html
- tests/reftests/text/font-color-gradient.html

**Comment by istoan** [comment]
@ysk2014 I may not have the right html2canvas version. Where can I find a compiled version with support for filters and stroke? Is there a way to download a html2canvas.js file?

**Comment by ysk2014** [comment]
@istoan you can git clone git@github.com:ysk2014/html2canvas.git and run npm start

**Comment by istoan** [comment]
I managed to clone that after installing the Git Desktop app. I then opened the folder with VS Code and opened Terminal inside VS Code. Then I typed: npm start and I got the following error:

> > html2canvas@1.0.0-rc.5 start C:\Users\Paul\Documents\GitHub\html2canvas
> > node tests/server
> 
> internal/modules/cjs/loader.js:584
>     throw err;
>     ^
> 
> Error: Cannot find module 'express'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (C:\Users\Paul\Documents\GitHub\html2canvas\tests\server.js:1:79)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! html2canvas@1.0.0-rc.5 start: `node tests/server`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the html2canvas@1.0.0-rc.5 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Paul\AppData\Roaming\npm-cache\_logs\2020-10-20T11_19_02_101Z-debug.log

What am I doing wrong? And, is there an easier way to get a compiled version? Can you upload one to your repository?

**Comment by istoan** [comment]
@ysk2014 I'm new to this. I believe I first had to install all the dependencies needed. I did npm install and got all of them. I then typed npm start and I got: 

> > html2canvas@1.0.0-rc.5 start C:\Users\Paul\Documents\GitHub\html2canvas
> > node tests/server
> 
> Server running on port 8080
> CORS server running on port 8081

But it seems I can't find a html2canvas.js file. Not sure how to actually compile one so I can use it in my project.

**Comment by ysk2014** [comment]
@istoan Run npm run build. A dist folder will be generated with the JS file you want

**Comment by istoan** [comment]
@ysk2014 I managed to compile the file and the results seem to be the same as with the other html2canvas.js file downloaded from https://github.com/niklasvh/html2canvas/suites/1187063696/artifacts/17429870 

This is how it looks inside my HTML page:
![Screenshot of HTML Elements](https://user-images.githubusercontent.com/8363583/96606343-da198c80-12ff-11eb-8bb3-212ddf9fbc11.png)

This is the results produced with the new html2canvas.js code:
![Capture with html2canvas](https://user-images.githubusercontent.com/8363583/96606349-dab22300-12ff-11eb-8aaf-1ca3b96acdc3.png)

**Comment by ysk2014** [comment]
@istoan Can you provide the code? It's easy for me to find problems.

**Comment by istoan** [comment]
@ysk2014 An example can be found here:
https://istoan.com/work/html2canvas-filters-test/

And the files for that example are attached
[html2canvas-filters-test.zip](https://github.com/niklasvh/html2canvas/files/5414937/html2canvas-filters-test.zip)

**Comment by ysk2014** [comment]
@istoan Sorry. Filter only supports img at present

**Comment by istoan** [comment]
@ysk2014 Oh, that's why I got those results. Do you know any library that can save an image from HTML elements with filters applied? I really need a solution for this in order to deliver the functionality my app had inside the old Flash based version.

**Comment by ysk2014** [comment]
@istoan You can try [dom-to-image](https://www.npmjs.com/package/dom-to-image). In fact, html2canvas can also be implemented, but the compatibility is not good

**Comment by istoan** [comment]
@ysk2014 Thank you very much! dom-to-image works as it should. You are a life saver!

**Comment by Ronkiro** [comment]
Any updates to this? dom-to-image is sadly not working well in my case. Html2canvas does everything correctly, the only problem is the filter

**Comment by Jashan66** [comment]
> Any updates to this? dom-to-image is sadly not working well in my case. Html2canvas does everything correctly, the only problem is the filter

+1

**Comment by AugustinMortier** [comment]
I would also appreciate <b>very much</b> this feature :)

**Comment by vrossi-dev** [comment]
> I would also appreciate very much this feature :)

+1

**Comment by hkanizawa** [comment]
> I would also appreciate very much this feature :)

+1

**Comment by Ronkiro** [comment]
For people looking for a solution that doesn't uses dom-to-image, i managed to make what i wanted by using Jimp.

See https://github.com/jimp-dev/jimp/issues/1194

**Comment by FranH20** [comment]
I have the same problem, the filter brightness() dosen't work.
