### ISSUE TITLE
Html2Canvas with AngularJs

### ISSUE THREAD

**Issue by DevQueen** [niklasvh/html2canvas#745]
I'm trying to use Html2canvas with Angular.  I receive the following error:

TypeError: Object doesn't support property or method 'setAttribute'
   at window.html2canvas (http://localhost/SSQV4/SSQV5/Scripts/html2canvas.js:602:5)
   at $scope.export (http://localhost/SSQV4/SSQV5/Scripts/app/Contractor/ContractorCtrl.js:48:17)
   at fn (Function code:2:277)
   at Anonymous function (http://localhost/SSQV4/SSQV5/Scripts/angular-touch.js:478:9)
   at Scope.prototype.$eval (http://localhost/SSQV4/SSQV5/Scripts/angular.js:15989:9)
   at Scope.prototype.$apply (http://localhost/SSQV4/SSQV5/Scripts/angular.js:16089:13)
   at Anonymous function (http://localhost/SSQV4/SSQV5/Scripts/angular-touch.js:477:7)
   at jQuery.event.dispatch (http://localhost/SSQV4/SSQV5/Scripts/jquery-1.8.2.js:3076:6)
   at eventHandle (http://localhost/SSQV4/SSQV5/Scripts/jquery-1.8.2.js:2694:5)

Here is my code:

```
            var myPic;
            html2canvas([document.getElementById('exportable').innerHTML], {
                onrendered: function (canvas) {
                    myPic = canvas.toDataUrl("image/jpeg");
                }
            });
```

Can anyone please help?

**Comment by ChandniGondhiya** [comment]
I am facing the same issue. Works well independently, but when I use it with Angular, generates similar error. 

TypeError: l.setAttribute is not a function
    at f (html2canvas.min.js:7)
    at getCanvas (questionnaire.js:207)
    at createPDF (questionnaire.js:190)
    at Scope.$scope.evaluatePIA_Threshold (questionnaire.js:145)
    at $parseFunctionCall (angular.js:12404)
    at callback (angular.js:21566)
    at Scope.$eval (angular.js:14466)
    at Scope.$apply (angular.js:14565)
    at HTMLFormElement.<anonymous> (angular.js:21571)
    at HTMLFormElement.m.event.dispatch (jquery.min.js:3)


My code : 

  function createPDF(){
        getCanvas().then(function(canvas){
        var img = canvas.toDataURL("image/png"),
            doc = new jsPDF({
                  unit:'px', 
                  format:'a4'
                });     
                doc.addImage(img, 'JPEG', 20, 20);
                doc.save('online-questionnaire.pdf');
                form.width(cache_width);
         });
        console.log("pdf created success");
    }
    
    // create canvas object
    function getCanvas(){
     form.width((a4[0]*1.33333) -80).css('max-width','none');
        console.log("after setting form width");
     return html2canvas(form,{
         imageTimeout:2000,
         removeContainer:true
        }); 
    }


Any help much appreciated!

**Comment by sandeepthomas** [comment]
try removing innerHTML from the code. 

 var myPic;
            html2canvas([document.getElementById('exportable')], {
                onrendered: function (canvas) {
                    myPic = canvas.toDataUrl("image/jpeg");
                }
            });
