### ISSUE TITLE
SVG in <img> breaks export in IE11

### ISSUE THREAD

**Issue by sefator** [niklasvh/html2canvas#898]
Exporting `<img src='some_image.svg'>` element with SVG content using IE11 ends with error:

`TypeError: Unable to get property 'svg' of undefined or null reference
   at SVGContainer.prototype.hasFabric (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:3214:5)
   at SVGContainer (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:3204:5)
   at ImageLoader.prototype.loadImage (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:1291:13)
   at Anonymous function (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:1276:17)
   at Anonymous function (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:1274:9)
   at ImageLoader.prototype.findImages (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:1248:5)
   at ImageLoader.prototype.fetch (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:1354:5)
   at NodeParser (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:1841:5)
   at renderWindow (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:992:5)
   at Anonymous function (http://10.0.2.2:9000/lib/html2canvas/dist/html2canvas.js:979:13)`

**Comment by atdiff** [comment]
@sefator do you have a jsFiddle with this example?  Curious to see how your SVGs are working.  I'm having little to no luck with getting my SVGs rendered at all with html2canvas.  Works decent, but not great, in Chrome - but not getting anywhere with IE.

**Comment by nearwood** [comment]
Also see #834, this sounds very familiar.

**Comment by oizie** [comment]
I am having an issue with this as well. Even trying to do:
import html2canvas from 'html2canvas';
  window.html2canvas = {
    svg: html2canvas.svg
  };
it will capture an blank image which is not the solution of course.

**Comment by petertflem** [comment]
I have the same issue. Does anyone know a fix for this?

```ERROR Error: Uncaught (in promise): TypeError: Unable to get property 'svg' of undefined or null reference
TypeError: Unable to get property 'svg' of undefined or null reference
   at SVGContainer.prototype.hasFabric (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:11627:5)
   at SVGNodeContainer (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:11670:5)
   at ImageLoader.prototype.loadImage (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9721:9)
   at Anonymous function (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9689:17)
   at Anonymous function (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9687:9)
   at ImageLoader.prototype.findImages (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9661:5)
   at ImageLoader.prototype.fetch (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9767:5)
   at NodeParser (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:10254:5)
   at renderWindow (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9405:5)
   at Anonymous function (http://eksportkreditt.dev/wp-content/themes/eksportkreditt/ng-form/dist/vendor.bundle.js:9392:13)```

**Comment by petertflem** [comment]
Possible fix: https://github.com/niklasvh/html2canvas/issues/834
Need ran into another error, so don't quite know if it works, but I no longer get the svg error.
