### ISSUE TITLE
DOMException: Failed to execute 'addColorStop' on 'CanvasGradient'

### ISSUE THREAD

**Issue by gaspar-tovar-civitas** [niklasvh/html2canvas#994]
Hi! hey so am using this library and it has worked really well until for some reason on an specific html it throws this error DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (-0.914214) is outside the range (0.0, 1.0).(…)

this is the full error!
DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (-0.914214) is outside the range (0.0, 1.0).
    at svg.Element.linearGradient.createGradient (bundle.js:7256:8)
    at svg.Property.getFillStyleDefinition (bundle.js:5938:18)
    at svg.Element.rect.setContext (bundle.js:6480:34)
    at svg.Element.rect.render (bundle.js:6362:11)
    at svg.Element.g.renderChildren (bundle.js:6390:23)
    at svg.Element.g.render (bundle.js:6372:17)
    at svg.Element.g.renderChildren (bundle.js:6390:23)
    at svg.Element.g.render (bundle.js:6372:17)
    at svg.Element.g.renderChildren (bundle.js:6390:23)
    at svg.Element.g.render (bundle.js:6372:17)

Anyone has any recomendations?

**Comment by niklasvh** [comment]
Should be fixed in 1.0.0
